import '../styles/globals.css';
import { createGlobalStyle, ThemeProvider } from 'styled-components';
import { UserContextWrapper } from '../store/user-context';
import Head from 'next/head';
const GlobalStyle = createGlobalStyle`
html,
body {
   padding: 0;
   margin: 0;
}
* {
   box-sizing: border-box;
}
a {
   color: inherit;
   text-decoration: none;
}


`;

const theme = {
   colors: {
      primary: '#F2F2F2',
      dark: '#222222',
      gray: '#707070',
      brown: '#A88C6A',
   },
};

function MyApp({ Component, pageProps }) {
   return (
      <>
         <GlobalStyle />
         <ThemeProvider theme={theme}>
            <UserContextWrapper>
               <Head>
                  <title>Innovant Assignment</title>
                  <meta
                     name="description"
                     content="Generated by create next app"
                  />
                  <link rel="icon" href="/favicon.ico" />
               </Head>
               <Component {...pageProps} />
            </UserContextWrapper>
         </ThemeProvider>
      </>
   );
}

export default MyApp;
